## **cleveland data**

## **Import Libraries**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msn

## **Read CSV file**

<p><strong>Age</strong>: Patients Age in years (Numeric)


<strong>Sex</strong>: Gender (Male : 1; Female : 0) (Nominal)


<strong>cp</strong>: Type of chest pain experienced by patient. This term categorized into 4 category.
0 typical angina, 1 atypical angina, 2 non- anginal pain, 3 asymptomatic (Nominal)

<strong>trestbps</strong>: patient's level of blood pressure at resting mode in mm/HG (Numerical)

<strong>chol</strong>: Serum cholesterol in mg/dl (Numeric)

<strong>fbs</strong>: Blood sugar levels on fasting > 120 mg/dl represents as 1 in case of true and 0 as false (Nominal)


<strong>restecg</strong>: Result of electrocardiogram while at rest are represented in 3 distinct values
0 : Normal 1: having ST-T wave abnormality (T wave inversions and/or ST elevation or depression of > 0.05 mV)
2: showing probable or definite left ventricular hypertrophyby Estes' criteria (Nominal)
thalach: Maximum heart rate achieved (Numeric)


<strong>exang</strong>: Angina induced by exercise 0 depicting NO 1 depicting Yes (Nominal)

<strong>oldpeak</strong>: Exercise induced ST-depression in relative with the state of rest (Numeric)
<strong>slope</strong>: ST segment measured in terms of slope during peak exercise
0: up sloping; 1: flat; 2: down sloping(Nominal)
<strong>ca</strong>: The number of major vessels (0–3)(nominal)
<strong>thal</strong>: A blood disorder called thalassemia
0: NULL 1: normal blood flow 2: fixed defect (no blood flow in some part of the heart) 3: reversible defect (a blood flow is observed but it is not normal(nominal)


<strong>target</strong>: It is the target variable which we have to predict 1 means patient is suffering from heart disease and 0 means patient is normal.<p>

In [2]:
sex_map = {"Male": 1, "Female" : 0}
cp_map = {"Typical angina": 0, "Atypical angina": 1,  "non- anginal pain": 2, "Asymptomatic": 3}
fbs_map = {"Normal": 0, "> 120 mg/dl": 1}
restecg_map = {"Normal": 0, "ST-T wave abnormality":1, "Ventricular hypertrophyby":3}
exang_map = {"No":0, "Yes":1}
slope_map = {"UP Sloping": 0, "Flat":1, "Down sloping": 2}
thal_map = {"NULL": 0, "normal blood flow":1, "fixed defect (no blood flow in some part of the heart)": 2, "reversible defect (a blood flow is observed but it is not normal(nominal)": 3 }
target_map = {"Patient is normal" :0, "Patient is suffering from heart disease":1}

In [3]:
df=pd.read_csv("Heart_disease_cleveland_new.csv");
df = df.dropna()

In [4]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,0,145,233,1,2,150,0,2.3,2,0,2,0
1,67,1,3,160,286,0,2,108,1,1.5,1,3,1,1
2,67,1,3,120,229,0,2,129,1,2.6,1,2,3,1
3,37,1,2,130,250,0,0,187,0,3.5,2,0,1,0
4,41,0,1,130,204,0,2,172,0,1.4,0,0,1,0

In [5]:
df.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
298,45,1,0,110,264,0,0,132,0,1.2,1,0,3,1
299,68,1,3,144,193,1,0,141,0,3.4,1,2,3,1
300,57,1,3,130,131,0,0,115,1,1.2,1,1,3,1
301,57,0,1,130,236,0,2,174,0,0.0,1,1,1,1
302,38,1,2,138,175,0,0,173,0,0.0,0,0,1,0

In [6]:
df.shape

(303, 14)

In [7]:
print('sex', df['sex'].unique())
print('cp', df['cp'].unique())
print('fbs', df['fbs'].unique())
print('restecg', df['restecg'].unique())
print('exang', df['exang'].unique())
print('slope', df['slope'].unique())
print('ca', df['ca'].unique())
print('thal', df['thal'].unique())
print('target', df['target'].unique())

sex [1 0]
cp [0 3 2 1]
fbs [1 0]
restecg [2 0 1]
exang [0 1]
slope [2 1 0]
ca [0 3 2 1]
thal [2 1 3]
target [0 1]

In [8]:
X=df[['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal']].values

In [9]:
y=df['target'].values

## **Splitting Dataset into training and testing by train_test_split**

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=22)

## ***1.Logistic Regression Model***

In [11]:
from sklearn.linear_model import LogisticRegression
model_logisticRegression=LogisticRegression()
model_logisticRegression.fit(X_train,y_train)

C:\Users\639pr\.conda\envs\heartgui-env\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [12]:
y_predict_lgr=model_logisticRegression.predict(X_test)

### **Model Evaluation**

In [13]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
acc_score = accuracy_score(y_test,y_predict_lgr)*100
print("Accuracy of the model by Logistic Regression is :",acc_score)
print(confusion_matrix(y_test,y_predict_lgr))

Accuracy of the model by Logistic Regression is : 85.71428571428571
[[47  5]
 [ 8 31]]

In [14]:
print(classification_report(y_test,y_predict_lgr))

              precision    recall  f1-score   support

           0       0.85      0.90      0.88        52
           1       0.86      0.79      0.83        39

    accuracy                           0.86        91
   macro avg       0.86      0.85      0.85        91
weighted avg       0.86      0.86      0.86        91

In [15]:
import pickle
import json

with open("model_logisticRegression.pkl", "wb") as f:
    pickle.dump(model_logisticRegression, f)
    
    
with open("model_logisticRegression_acc.json", "w") as fj:
    fj.write('{"acc":"'+str(acc_score)+'"}')
    

with open('model_logisticRegression_acc.json', 'r') as f:
    data = json.load(f)
    print(data["acc"])
    print("{:.2f}".format(float(data["acc"])))
    print(type(data["acc"]))

85.71428571428571
85.71
<class 'str'>

## ***2.KNN***

In [16]:
from sklearn.neighbors import KNeighborsClassifier
model_kNeighborsClassifier=KNeighborsClassifier()

In [17]:
model_kNeighborsClassifier.fit(X_train,y_train)

KNeighborsClassifier()

In [18]:
y_predict_knn=model_kNeighborsClassifier.predict(X_test)

### **Model Evaluation**

In [19]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
acc_score = accuracy_score(y_test,y_predict_knn)*100
print("Accuracy of the model by KNN is :",acc_score)

Accuracy of the model by KNN is : 65.93406593406593

In [20]:
print(confusion_matrix(y_test,y_predict_knn))

[[39 13]
 [18 21]]

In [21]:
print(classification_report(y_test,y_predict_knn))

              precision    recall  f1-score   support

           0       0.68      0.75      0.72        52
           1       0.62      0.54      0.58        39

    accuracy                           0.66        91
   macro avg       0.65      0.64      0.65        91
weighted avg       0.66      0.66      0.66        91

In [22]:
with open("model_kNeighborsClassifier.pkl", "wb") as f:
    pickle.dump(model_kNeighborsClassifier, f)
    
    
with open("model_kNeighborsClassifier_acc.json", "w") as fj:
    fj.write('{"acc":"'+str(acc_score)+'"}')
    

with open('model_kNeighborsClassifier_acc.json', 'r') as f:
    data = json.load(f)
    print(data["acc"])
    print("{:.2f}".format(float(data["acc"])))
    print(type(data["acc"]))

65.93406593406593
65.93
<class 'str'>

## ***3.Decision Tree*** ##

In [23]:
from sklearn import tree

model_decisionTreeClassifier = tree.DecisionTreeClassifier()   # empty model of the decision tree
model_decisionTreeClassifier.fit(X_train,y_train)

DecisionTreeClassifier()

In [24]:
y_predict_tree=model_decisionTreeClassifier.predict(X_test)

### **Model Evaluation**

In [25]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
acc_score = accuracy_score(y_test,y_predict_tree)*100
print("Accuracy of the model by Decision Tree is : ",acc_score)

Accuracy of the model by Decision Tree is :  76.92307692307693

In [26]:
print(confusion_matrix(y_test,y_predict_tree))

[[40 12]
 [ 9 30]]

In [27]:
print(classification_report(y_test,y_predict_tree))

              precision    recall  f1-score   support

           0       0.82      0.77      0.79        52
           1       0.71      0.77      0.74        39

    accuracy                           0.77        91
   macro avg       0.77      0.77      0.77        91
weighted avg       0.77      0.77      0.77        91

In [28]:
with open("model_decisionTreeClassifier.pkl", "wb") as f:
    pickle.dump(model_decisionTreeClassifier, f)
    
    
with open("model_decisionTreeClassifier_acc.json", "w") as fj:
    fj.write('{"acc":"'+str(acc_score)+'"}')
    

with open('model_decisionTreeClassifier_acc.json', 'r') as f:
    data = json.load(f)
    print(data["acc"])
    print("{:.2f}".format(float(data["acc"])))
    print(type(data["acc"]))

76.92307692307693
76.92
<class 'str'>

# <h1>4.SVM  (svc) </h1>

In [29]:
from sklearn import svm
model_svm = svm.SVC()
model_svm.fit(X_train,y_train)

SVC()

In [30]:
y_predict_svc=model_svm.predict(X_test)

In [31]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
acc_score = accuracy_score(y_test,y_predict_svc)*100
print("Accuracy of the model by SVM is : ",accuracy_score(y_test,y_predict_tree)*100)

Accuracy of the model by SVM is :  76.92307692307693

In [32]:
print(confusion_matrix(y_test,y_predict_tree))

[[40 12]
 [ 9 30]]

In [33]:
print(classification_report(y_test,y_predict_tree))

              precision    recall  f1-score   support

           0       0.82      0.77      0.79        52
           1       0.71      0.77      0.74        39

    accuracy                           0.77        91
   macro avg       0.77      0.77      0.77        91
weighted avg       0.77      0.77      0.77        91

In [34]:
with open("model_svm.pkl", "wb") as f:
    pickle.dump(model_svm, f)
    
    
with open("model_svm_acc.json", "w") as fj:
    fj.write('{"acc":"'+str(acc_score)+'"}')
    

with open('model_svm_acc.json', 'r') as f:
    data = json.load(f)
    print(data["acc"])
    print("{:.2f}".format(float(data["acc"])))
    print(type(data["acc"]))

68.13186813186813
68.13
<class 'str'>

In [35]:
from sklearn.ensemble import VotingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score



# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize individual models
svc = SVC(probability=True)
knn = KNeighborsClassifier()
logreg = LogisticRegression(max_iter=1000)
dtree = DecisionTreeClassifier()

# Create a Voting Classifier (hard voting)
voting_clf = VotingClassifier(
    estimators=[
        ('svc', svc),
        ('knn', knn),
        ('logreg', logreg),
        ('dtree', dtree)
    ],
    voting='hard'  # Can change to 'soft' if you want probability-based voting
)

# Train ensemble model
voting_clf.fit(X_train, y_train)

# Predict and evaluate
y_pred = voting_clf.predict(X_test)
acc_score = accuracy_score(y_test, y_pred)*100
print("Ensemble Accuracy:",acc_score)

Ensemble Accuracy: 75.40983606557377

In [36]:
with open("voting_clf.pkl", "wb") as f:
    pickle.dump(voting_clf, f)
    
    
with open("voting_clf_acc.json", "w") as fj:
    fj.write('{"acc":"'+str(acc_score)+'"}')
    

with open('voting_clf_acc.json', 'r') as f:
    data = json.load(f)
    print(data["acc"])
    print("{:.2f}".format(float(data["acc"])))
    print(type(data["acc"]))

75.40983606557377
75.41
<class 'str'>

In [37]:
y_predict_tree = voting_clf.predict([[67.0, 1.0, 4.0, 160.0, 286.0, 0.0, 2.0, 108.0, 1.0, 1.5, 2.0, 3.0, 3.0 ]])
y_predict_tree

array([1], dtype=int64)

In [38]:
row_index = 1
row_array = df.iloc[row_index].values  # Or use .to_numpy()

print("Row as array:", row_array)
print("[[", end="");
for x in range(0, len(row_array)-1):
    print(row_array[x], end=", " if x < len(row_array) - 2 else " ")
print("]]")

Row as array: [ 67.    1.    3.  160.  286.    0.    2.  108.    1.    1.5   1.    3.
   1.    1. ]
[[67.0, 1.0, 3.0, 160.0, 286.0, 0.0, 2.0, 108.0, 1.0, 1.5, 1.0, 3.0, 1.0 ]]